(function(){
  const API_BASE = 'https://api.overwatcheld.com';
  const TOKEN_KEYS = ['oweld_session_token','oweldToken','sessionToken','token'];
  function token(){ for(const k of TOKEN_KEYS){ const v=localStorage.getItem(k); if(v) return v; } return ''; }
  function guildId(){ const q=new URLSearchParams(location.search); return q.get('guildId')||localStorage.getItem('oweld_guild_id')||localStorage.getItem('owGuildId')||''; }
  function setGuildId(v){ if(v) { localStorage.setItem('oweld_guild_id',v); localStorage.setItem('owGuildId',v); } }
  function esc(v){ return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }
  function pick(o, keys, fallback=''){ for(const k of keys){ if(o && o[k] !== undefined && o[k] !== null && String(o[k]).trim() !== '') return o[k]; } return fallback; }
  function rows(d){
    if(Array.isArray(d)) return d;
    if(!d || typeof d !== 'object') return [];
    const keys=['data','items','rows','results','trucks','fleet','garages','loads','jobs','drivers','roster','awards','endorsements','bols','documents'];
    for(const k of keys){ if(Array.isArray(d[k])) return d[k]; }
    if(d.data && typeof d.data === 'object') return rows(d.data);
    return [];
  }
  async function request(path){
    const gid=guildId();
    const sep=path.includes('?')?'&':'?';
    const full = `${API_BASE}${path}${gid && !/[?&]guildId=/.test(path) ? sep+'guildId='+encodeURIComponent(gid) : ''}`;
    const headers={Accept:'application/json'};
    const t=token(); if(t){ headers.Authorization='Bearer '+t; headers['X-OverWatch-Session']=t; }
    const res=await fetch(full,{cache:'no-store',credentials:'include',headers});
    const text=await res.text();
    let data={}; try{data=text?JSON.parse(text):{};}catch{data={raw:text};}
    if(!res.ok) throw new Error(data.error||data.message||`${res.status} ${res.statusText}`);
    return data;
  }
  async function best(paths){
    let last;
    for(const p of paths){ try{ const data=await request(p); return {path:p,data}; }catch(e){ last=e; } }
    throw last||new Error('No endpoint returned data');
  }
  function shell(title, subtitle){
    document.body.innerHTML = `<header class="header"><nav class="nav"><a class="brand" href="/"><span class="brand-mark">OW</span><span>OverWatch ELD</span></a><div class="nav-links"><a href="/portal/">Portal</a><a href="/operations/">Operations</a><a href="/fleet.html">Fleet</a><a href="/garages.html">Garages</a><a href="/loads.html">Loads</a><a href="/roster.html">Roster</a></div></nav></header><main class="wrap ow-live-main"><div class="kicker">Live Portal Data</div><h1>${esc(title)}</h1><p class="lead">${esc(subtitle)}</p><div class="ow-live-toolbar"><input id="owGuildInput" class="input" placeholder="Discord server / guild ID" value="${esc(guildId())}"><button id="owSaveGuild" class="btn secondary">Load</button><button id="owRefresh" class="btn">Refresh</button><span id="owStatus" class="ow-muted">Ready</span></div><section id="owContent" class="ow-live-grid"></section></main><footer class="footer"><div class="wrap"><span>OverWatch ELD © 2026 Gas Monkey Creations</span></div></footer>`;
    document.getElementById('owSaveGuild').onclick=()=>{setGuildId(document.getElementById('owGuildInput').value.trim()); const u=new URL(location.href); if(guildId()) u.searchParams.set('guildId',guildId()); location.href=u.toString();};
  }
  function status(t,bad){ const el=document.getElementById('owStatus'); if(el){ el.textContent=t; el.style.color=bad?'#ffb4b4':''; } }
  function card(title, body, meta=''){ return `<article class="ow-live-card"><h3>${esc(title)}</h3><div>${body}</div>${meta?`<p class="ow-muted">${esc(meta)}</p>`:''}</article>`; }
  function empty(title, hint){ return card(title, `<p>${esc(hint)}</p>`); }
  function renderFleet(){ shell('Fleet Trucks','Live trucks synced from the OverWatch ELD VTC portal.'); document.getElementById('owRefresh').onclick=load; load(); async function load(){ status('Loading fleet...',false); try{ const r=await best(['/api/vtc/portal/fleet','/api/vtc/fleet','/api/fleet','/api/management/fleet']); const list=rows(r.data); document.getElementById('owContent').innerHTML=list.length?list.map(t=>card((pick(t,['truckNumber','TruckNumber'])?('#'+pick(t,['truckNumber','TruckNumber'])+' '):'')+(pick(t,['name','Name','model','Model'],'Truck')),`<p><b>Driver:</b> ${esc(pick(t,['driver','Driver','driverName','DriverName','assignedDriver'],'Unassigned'))}</p><p><b>Plate:</b> ${esc(pick(t,['plate','Plate','licensePlate'],'N/A'))}</p><p><b>Location:</b> ${esc(pick(t,['location','Location','garage','Garage'],'Unknown'))}</p><p><b>Status:</b> ${esc(pick(t,['status','Status','condition','Condition'],'Available'))}</p><p><b>Odometer:</b> ${esc(pick(t,['odometer','Odometer','miles','Mileage'],'-'))}</p>`,pick(t,['notes','Notes','updatedUtc','lastUpdated'],''))).join(''):empty('No fleet trucks found','Add/sync trucks in the ELD or portal admin, then refresh.'); status(`Loaded ${list.length} truck${list.length===1?'':'s'} from ${r.path}`,false);}catch(e){document.getElementById('owContent').innerHTML=empty('Fleet unavailable',e.message); status(e.message,true);} } }
  function renderGarages(){ shell('Garages','Live garage locations and capacity from the VTC portal.'); document.getElementById('owRefresh').onclick=load; load(); async function load(){ status('Loading garages...',false); try{ const r=await best(['/api/vtc/portal/garages','/api/vtc/garages','/api/garages']); const list=rows(r.data); document.getElementById('owContent').innerHTML=list.length?list.map(g=>card(pick(g,['city','City','cityName','CityName','name','Name'],'Garage'),`<p><b>Region:</b> ${esc([pick(g,['state','State'],''),pick(g,['country','Country'],'')].filter(Boolean).join(', ')||'-')}</p><p><b>Slots:</b> ${esc(pick(g,['slots','Slots','truckCapacity','TruckCapacity'],'-'))}</p><p><b>Size:</b> ${esc(pick(g,['size','Size'],'-'))}</p><p><b>Owned:</b> ${esc(String(pick(g,['isOwned','IsOwned'],'true')))}</p><p>${esc(pick(g,['notes','Notes','description'],'')).replace(/\n/g,'<br>')}</p>`)).join(''):empty('No garages found','Add garages in portal admin, then refresh.'); status(`Loaded ${list.length} garage${list.length===1?'':'s'} from ${r.path}`,false);}catch(e){document.getElementById('owContent').innerHTML=empty('Garages unavailable',e.message); status(e.message,true);} } }
  function renderLoads(){ shell('Operations Loads & BOLs','Live dispatch loads, completed loads, and BOL-related records.'); document.getElementById('owRefresh').onclick=load; load(); async function load(){ status('Loading loads...',false); try{ const r=await best(['/api/vtc/portal/loads','/api/dispatch/loads','/api/loads','/api/dispatch/board']); const list=rows(r.data); document.getElementById('owContent').innerHTML=list.length?list.map(l=>card(pick(l,['loadNumber','LoadNumber','id','Id'],'Load'),`<p><b>Status:</b> ${esc(pick(l,['status','Status'],'Available'))}</p><p><b>Route:</b> ${esc(pick(l,['origin','Origin','pickup','Pickup'],'-'))} → ${esc(pick(l,['destination','Destination','dropoff','Dropoff'],'-'))}</p><p><b>Cargo:</b> ${esc(pick(l,['cargo','Cargo','commodity','Commodity'],'-'))}</p><p><b>Driver:</b> ${esc(pick(l,['assignedDriver','AssignedDriver','driver','Driver'],'Unassigned'))}</p><p><b>Truck:</b> ${esc(pick(l,['assignedTruck','AssignedTruck','truck','Truck'],'-'))}</p><p><b>BOL:</b> ${esc(pick(l,['bolNumber','BolNumber','bolStatus','BolStatus','bolFile','bolUrl','documentStatus'],'No BOL status recorded'))}</p>`,pick(l,['updatedUtc','createdUtc','date','Date'],''))).join(''):empty('No operations loads found','Create/sync loads from dispatch or the ELD app, then refresh.'); status(`Loaded ${list.length} load${list.length===1?'':'s'} from ${r.path}`,false);}catch(e){document.getElementById('owContent').innerHTML=empty('Loads unavailable',e.message); status(e.message,true);} } }
  function renderRoster(){ shell('Roster Endorsements','Live driver roster, endorsements, certifications, and awards.'); document.getElementById('owRefresh').onclick=load; load(); async function load(){ status('Loading roster...',false); try{ const r=await best(['/api/vtc/portal/drivers','/api/management/drivers','/api/vtc/roster','/api/portal/me']); let list=rows(r.data); if(!list.length && r.data && (r.data.driver||r.data.profile||r.data.me)) list=[r.data.driver||r.data.profile||r.data.me]; document.getElementById('owContent').innerHTML=list.length?list.map(d=>{ const endorsements=rows(pick(d,['endorsements','Endorsements'],[])); const awards=rows(pick(d,['awards','Awards','certifications','Certifications'],[])); const endText=endorsements.length?endorsements.map(x=>typeof x==='string'?x:pick(x,['name','Name','title','Title','endorsement'],'Endorsement')).join(', '):pick(d,['endorsement','Endorsement','licenseEndorsements'],'None listed'); const awardText=awards.length?awards.map(x=>typeof x==='string'?x:pick(x,['name','Name','title','Title','award'],'Award')).join(', '):pick(d,['achievement','Achievement','award','Award'],'None listed'); return card(pick(d,['userName','name','Name','discordUsername','driverName'],'Driver'),`<p><b>Role:</b> ${esc(pick(d,['role','Role'],'Driver'))}</p><p><b>Truck:</b> ${esc(pick(d,['currentTruck','assignedTruck','AssignedTruck'],'Unassigned'))}</p><p><b>Status:</b> ${esc(pick(d,['status','Status'],'Member'))}</p><p><b>Endorsements:</b> ${esc(endText)}</p><p><b>Awards/Certifications:</b> ${esc(awardText)}</p><p><b>Miles:</b> ${esc(pick(d,['totalMileage','TotalMiles','mileage'],'0'))}</p>`); }).join(''):empty('No roster found','Sync drivers or roster from portal admin, then refresh.'); status(`Loaded ${list.length} driver${list.length===1?'':'s'} from ${r.path}`,false);}catch(e){document.getElementById('owContent').innerHTML=empty('Roster unavailable',e.message); status(e.message,true);} } }
  window.OWLive={renderFleet,renderGarages,renderLoads,renderRoster,rows,pick,esc,best,request,guildId,setGuildId};
})();
